/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCManagePropertyValueTypesDialog.java
 *
 * Created on 13.09.2010, 14:28:26
 */

package edacc;

import edacc.model.NoConnectionToDBException;
import edacc.properties.PropertyValueTypeTableModel;
import edacc.properties.PropertyValueTypesController;
import edacc.satinstances.PropertyValueType;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rretz
 */
public class EDACCManagePropertyValueTypesDialog extends javax.swing.JDialog {
    private PropertyValueTypesController controller;
    private PropertyValueTypeTableModel propValueTypeTableModel;
    private File file;

    /** Creates new form EDACCManagePropertyValueTypesDialog */
    public EDACCManagePropertyValueTypesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // initialize tablePropertyValueTypes
        propValueTypeTableModel = new PropertyValueTypeTableModel();
        tablePropertyValueTypes.setModel(propValueTypeTableModel);
        tablePropertyValueTypes.setRowSorter(new TableRowSorter<PropertyValueTypeTableModel>(propValueTypeTableModel));

        controller = new PropertyValueTypesController(this, tablePropertyValueTypes);
    }

     /**
     * Initialize and chargs the tableSolverPropertys and the comboBoxSolverPropertyValueType with the corresponding items.
     */
    public void initialize() {
        try {
            controller.loadPropertyValueTypes();
        } catch (NoConnectionToDBException ex) {
            Logger.getLogger(EDACCManagePropertyValueTypesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EDACCManagePropertyValueTypesDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EDACCManagePropertyValueTypesDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panelMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePropertyValueTypes = new javax.swing.JTable();
        panelInputFields = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        labelTypeClass = new javax.swing.JLabel();
        buttonChooseClassFile = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonDone = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();

        jFileChooser1.setName("jFileChooser1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCManagePropertyValueTypesDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        panelMain.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelMain.border.title"))); // NOI18N
        panelMain.setName("panelMain"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablePropertyValueTypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePropertyValueTypes.setName("tablePropertyValueTypes"); // NOI18N
        jScrollPane1.setViewportView(tablePropertyValueTypes);

        panelInputFields.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelInputFields.setName("panelInputFields"); // NOI18N

        labelName.setText(resourceMap.getString("labelName.text")); // NOI18N
        labelName.setName("labelName"); // NOI18N

        textFieldName.setText(resourceMap.getString("textFieldName.text")); // NOI18N
        textFieldName.setEnabled(false);
        textFieldName.setName("textFieldName"); // NOI18N

        labelTypeClass.setText(resourceMap.getString("labelTypeClass.text")); // NOI18N
        labelTypeClass.setName("labelTypeClass"); // NOI18N

        buttonChooseClassFile.setText(resourceMap.getString("buttonChooseClassFile.text")); // NOI18N
        buttonChooseClassFile.setEnabled(false);
        buttonChooseClassFile.setName("buttonChooseClassFile"); // NOI18N
        buttonChooseClassFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseClassFileActionPerformed(evt);
            }
        });

        buttonSave.setText(resourceMap.getString("buttonSave.text")); // NOI18N
        buttonSave.setEnabled(false);
        buttonSave.setName("buttonSave"); // NOI18N
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputFieldsLayout = new javax.swing.GroupLayout(panelInputFields);
        panelInputFields.setLayout(panelInputFieldsLayout);
        panelInputFieldsLayout.setHorizontalGroup(
            panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputFieldsLayout.createSequentialGroup()
                        .addGroup(panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelTypeClass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonChooseClassFile)
                            .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonSave))
                .addContainerGap())
        );

        panelInputFieldsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonChooseClassFile, buttonSave});

        panelInputFieldsLayout.setVerticalGroup(
            panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelInputFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTypeClass)
                    .addComponent(buttonChooseClassFile))
                .addGap(18, 18, 18)
                .addComponent(buttonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInputFieldsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonChooseClassFile, buttonSave});

        buttonDone.setText(resourceMap.getString("buttonDone.text")); // NOI18N
        buttonDone.setName("buttonDone"); // NOI18N
        buttonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDoneActionPerformed(evt);
            }
        });

        buttonNew.setText(resourceMap.getString("buttonNew.text")); // NOI18N
        buttonNew.setName("buttonNew"); // NOI18N
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelInputFields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(buttonDone)
                    .addComponent(buttonNew, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInputFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDone))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDoneActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonDoneActionPerformed

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        controller.newPropertyValueType();
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonChooseClassFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseClassFileActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        this.file = jFileChooser1.getSelectedFile();
    }//GEN-LAST:event_buttonChooseClassFileActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if(file != null){
            controller.createNewPropertyValueType();
        }else {
            JOptionPane.showMessageDialog(this,
                "No class type file selected.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EDACCManagePropertyValueTypesDialog dialog = new EDACCManagePropertyValueTypesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseClassFile;
    private javax.swing.JButton buttonDone;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonSave;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTypeClass;
    private javax.swing.JPanel panelInputFields;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTable tablePropertyValueTypes;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables

    public void enablePropertyValueTypeInputFields(boolean enable) {
        this.textFieldName.setEnabled(enable);
        this.buttonSave.setEnabled(enable);
        this.buttonChooseClassFile.setEnabled(enable);
        file = null;
    }

    public void showPropertyValueType(PropertyValueType propertyValueType) {
        this.enablePropertyValueTypeInputFields(true);
        this.textFieldName.setText(propertyValueType.getName());
    }
}
