/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCStatusCodeDlg.java
 *
 * Created on 19.09.2011, 19:44:16
 */

package edacc;

import edacc.model.StatusCode;
import edacc.model.StatusCodeDAO;
import edacc.statuscodes.StatusCodeListModel;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dgall
 */
public class EDACCStatusCodeDlg extends javax.swing.JDialog {

    private StatusCodeListModel listModel; 
    
    /** Creates new form EDACCStatusCodeDlg */
    public EDACCStatusCodeDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            listModel = new StatusCodeListModel();
            listStatusCodes.setModel(listModel);
        } catch (SQLException ex) {
            Logger.getLogger(EDACCStatusCodeDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listStatusCodes = new javax.swing.JList();
        bNew = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listStatusCodes.setName("listStatusCodes"); // NOI18N
        jScrollPane1.setViewportView(listStatusCodes);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCStatusCodeDlg.class);
        bNew.setText(resourceMap.getString("bNew.text")); // NOI18N
        bNew.setName("bNew"); // NOI18N
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });

        bDelete.setText(resourceMap.getString("bDelete.text")); // NOI18N
        bDelete.setName("bDelete"); // NOI18N
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private EDACCNewStatusCodeDlg newStatusCodeDlg;
    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        if (newStatusCodeDlg == null)
            newStatusCodeDlg = new EDACCNewStatusCodeDlg(null, true);
        newStatusCodeDlg.setVisible(true);
    }//GEN-LAST:event_bNewActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // show warning first
       /* final int userAnswer = JOptionPane.showConfirmDialog(this,
                "The selected status codes will be deleted. Do you wish to continue?",
                "Delete selected status codes",
                JOptionPane.YES_NO_OPTION);
        if (userAnswer == JOptionPane.NO_OPTION) {
            return;
        }

        for (Object e : listStatusCodes.getSelectedValues()) {
            StatusCode c = (StatusCode) e;
            listModel.removeStatusCode(c);
            c.setDeleted();
            try {
                StatusCodeDAO.save(c);
            } catch (SQLException ex) {
                Logger.getLogger(EDACCStatusCodeDlg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
*/
    }//GEN-LAST:event_bDeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EDACCStatusCodeDlg dialog = new EDACCStatusCodeDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listStatusCodes;
    // End of variables declaration//GEN-END:variables

}
