/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCManageDBMode.java
 *
 * Created on 03.01.2010, 16:02:23
 */
package edacc;

import edacc.manageDB.*;

/**
 *
 * @author rretz
 */
public class EDACCManageDBMode extends javax.swing.JPanel {

     public ManageDBInstances manageDBInstances;

     public EDACCManageDBMode(){
        initComponents();
         manageDBInstances = new ManageDBInstances(this, panelManageDBInstances, jFileChooserManageDBInstance );
     }

     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserManageDBInstance = new javax.swing.JFileChooser();
        manageDBPane = new javax.swing.JTabbedPane();
        panelManageDBSolver = new javax.swing.JPanel();
        panelManageDBInstances = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInstances = new javax.swing.JTable();
        btnAddInstances = new javax.swing.JButton();
        btnRemoveInstances = new javax.swing.JButton();
        btnRefreshTableInstances = new javax.swing.JButton();
        btnSaveInstances = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();

        jFileChooserManageDBInstance.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooserManageDBInstance.setName("jFileChooserManageDBInstance"); // NOI18N

        setName("Form"); // NOI18N

        manageDBPane.setName("manageDBPane"); // NOI18N

        panelManageDBSolver.setName("panelManageDBSolver"); // NOI18N

        javax.swing.GroupLayout panelManageDBSolverLayout = new javax.swing.GroupLayout(panelManageDBSolver);
        panelManageDBSolver.setLayout(panelManageDBSolverLayout);
        panelManageDBSolverLayout.setHorizontalGroup(
            panelManageDBSolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        panelManageDBSolverLayout.setVerticalGroup(
            panelManageDBSolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        manageDBPane.addTab("Solvers", panelManageDBSolver);

        panelManageDBInstances.setName("panelManageDBInstances"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableInstances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableInstances.setName("tableInstances"); // NOI18N
        jScrollPane1.setViewportView(tableInstances);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCManageDBMode.class);
        btnAddInstances.setText(resourceMap.getString("btnAddInstances.text")); // NOI18N
        btnAddInstances.setName("btnAddInstances"); // NOI18N
        btnAddInstances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInstancesActionPerformed(evt);
            }
        });

        btnRemoveInstances.setText(resourceMap.getString("btnRemoveInstances.text")); // NOI18N
        btnRemoveInstances.setName("btnRemoveInstances"); // NOI18N

        btnRefreshTableInstances.setText(resourceMap.getString("btnRefreshTableInstances.text")); // NOI18N
        btnRefreshTableInstances.setName("btnRefreshTableInstances"); // NOI18N

        btnSaveInstances.setText(resourceMap.getString("btnSaveInstances.text")); // NOI18N
        btnSaveInstances.setName("btnSaveInstances"); // NOI18N

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N

        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N

        javax.swing.GroupLayout panelManageDBInstancesLayout = new javax.swing.GroupLayout(panelManageDBInstances);
        panelManageDBInstances.setLayout(panelManageDBInstancesLayout);
        panelManageDBInstancesLayout.setHorizontalGroup(
            panelManageDBInstancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageDBInstancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageDBInstancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelManageDBInstancesLayout.createSequentialGroup()
                        .addComponent(btnAddInstances)
                        .addGap(10, 10, 10)
                        .addComponent(btnRemoveInstances)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefreshTableInstances)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveInstances))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        panelManageDBInstancesLayout.setVerticalGroup(
            panelManageDBInstancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageDBInstancesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelManageDBInstancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveInstances)
                    .addComponent(btnRefreshTableInstances)
                    .addComponent(btnFilter)
                    .addComponent(btnAddInstances)
                    .addComponent(btnSaveInstances)
                    .addComponent(btnCancel))
                .addGap(39, 39, 39))
        );

        manageDBPane.addTab("Instances", panelManageDBInstances);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(manageDBPane, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(manageDBPane, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddInstancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInstancesActionPerformed
        manageDBInstances.addInstances();
    }//GEN-LAST:event_btnAddInstancesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInstances;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnRefreshTableInstances;
    private javax.swing.JButton btnRemoveInstances;
    private javax.swing.JButton btnSaveInstances;
    private javax.swing.JFileChooser jFileChooserManageDBInstance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane manageDBPane;
    private javax.swing.JPanel panelManageDBInstances;
    private javax.swing.JPanel panelManageDBSolver;
    private javax.swing.JTable tableInstances;
    // End of variables declaration//GEN-END:variables
}
