/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCManagePropertyMode.java
 *
 * Created on 01.09.2010, 13:16:04
 */

package edacc;

import edacc.properties.ManageSolverProperties;
import edacc.properties.SolverPropertyTableModel;
import edacc.properties.SolverPropertyValueComboBoxModel;
import edacc.satinstances.PropertyValueTypeManager;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rretz
 */
public class EDACCManagePropertyMode extends javax.swing.JPanel {
    private ManageSolverProperties manageSolverProperties;
    private SolverPropertyTableModel solPropertyTableModel;
    private SolverPropertyValueComboBoxModel solPropTypeValueComModel;

    /** Creates new form EDACCManagePropertyMode */
    public EDACCManagePropertyMode() {
        initComponents();

        // initialize tableResultProperty
        solPropertyTableModel = new SolverPropertyTableModel();
        tableSovlerProperty.setRowSorter(new TableRowSorter<SolverPropertyTableModel>(solPropertyTableModel));

        manageSolverProperties = new ManageSolverProperties(this, panelManageSolverProperty, tableSovlerProperty);

        // initialize comboBoxSolverPropertyValuetype
        solPropTypeValueComModel = new SolverPropertyValueComboBoxModel();
        solPropTypeValueComModel.addPropertyValueTypes(PropertyValueTypeManager.getInstance().getAll());
        comboBoxSolverPropertyValuetype.setModel(solPropTypeValueComModel);

        // initialize comboBoxSolverPropertyType
        String[] solPropTypes = {"ResultFile", "ClientOutput", "Parameter"};

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePropertyPane = new javax.swing.JTabbedPane();
        panelManageSolverProperty = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelMangeSolverPropertyShow = new javax.swing.JPanel();
        panelManageSolverPropertyShowButtons = new javax.swing.JPanel();
        buttonNewSolverProperty = new javax.swing.JButton();
        buttonRemoveSolverProperty = new javax.swing.JButton();
        panelManageSolverPropertyTable = new javax.swing.JScrollPane();
        tableSovlerProperty = new javax.swing.JTable();
        panelManageSolverPropertyEdit = new javax.swing.JPanel();
        panelManageSolverPropertyEditButtons = new javax.swing.JPanel();
        buttonSaveSolverProperty = new javax.swing.JButton();
        panelManageSolverPropertyEditInput = new javax.swing.JPanel();
        textSolverPropertyFieldName = new javax.swing.JTextField();
        labelSolverPropertyname = new javax.swing.JLabel();
        textSolvertPropertyFieldPrefix = new javax.swing.JTextField();
        labelSolverPropertyPrefix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultPropertyDescription = new javax.swing.JTextArea();
        labelSolverPropertyDescription = new javax.swing.JLabel();
        comboBoxSolverPropertyValuetype = new javax.swing.JComboBox();
        labelSolverPropertyValuetype = new javax.swing.JLabel();
        buttonSolverPropertyAddValueType = new javax.swing.JButton();
        labeSolverPropertyType = new javax.swing.JLabel();
        comboBoxSolverPropertyType = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        managePropertyPane.setName("managePropertyPane"); // NOI18N

        panelManageSolverProperty.setName("panelManageSolverProperty"); // NOI18N

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.8);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        panelMangeSolverPropertyShow.setName("panelMangeSolverPropertyShow"); // NOI18N

        panelManageSolverPropertyShowButtons.setName("panelManageSolverPropertyShowButtons"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCManagePropertyMode.class);
        buttonNewSolverProperty.setText(resourceMap.getString("buttonNewSolverProperty.text")); // NOI18N
        buttonNewSolverProperty.setName("buttonNewSolverProperty"); // NOI18N
        buttonNewSolverProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewSolverPropertyActionPerformed(evt);
            }
        });

        buttonRemoveSolverProperty.setText(resourceMap.getString("buttonRemoveSolverProperty.text")); // NOI18N
        buttonRemoveSolverProperty.setName("buttonRemoveSolverProperty"); // NOI18N

        javax.swing.GroupLayout panelManageSolverPropertyShowButtonsLayout = new javax.swing.GroupLayout(panelManageSolverPropertyShowButtons);
        panelManageSolverPropertyShowButtons.setLayout(panelManageSolverPropertyShowButtonsLayout);
        panelManageSolverPropertyShowButtonsLayout.setHorizontalGroup(
            panelManageSolverPropertyShowButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyShowButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonNewSolverProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemoveSolverProperty)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        panelManageSolverPropertyShowButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonNewSolverProperty, buttonRemoveSolverProperty});

        panelManageSolverPropertyShowButtonsLayout.setVerticalGroup(
            panelManageSolverPropertyShowButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyShowButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageSolverPropertyShowButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNewSolverProperty)
                    .addComponent(buttonRemoveSolverProperty))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelManageSolverPropertyShowButtonsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonNewSolverProperty, buttonRemoveSolverProperty});

        panelManageSolverPropertyTable.setName("panelManageSolverPropertyTable"); // NOI18N

        tableSovlerProperty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSovlerProperty.setName("tableSovlerProperty"); // NOI18N
        panelManageSolverPropertyTable.setViewportView(tableSovlerProperty);

        javax.swing.GroupLayout panelMangeSolverPropertyShowLayout = new javax.swing.GroupLayout(panelMangeSolverPropertyShow);
        panelMangeSolverPropertyShow.setLayout(panelMangeSolverPropertyShowLayout);
        panelMangeSolverPropertyShowLayout.setHorizontalGroup(
            panelMangeSolverPropertyShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMangeSolverPropertyShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMangeSolverPropertyShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelManageSolverPropertyTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(panelManageSolverPropertyShowButtons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMangeSolverPropertyShowLayout.setVerticalGroup(
            panelMangeSolverPropertyShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMangeSolverPropertyShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelManageSolverPropertyTable, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelManageSolverPropertyShowButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(panelMangeSolverPropertyShow);

        panelManageSolverPropertyEdit.setName("panelManageSolverPropertyEdit"); // NOI18N

        panelManageSolverPropertyEditButtons.setName("panelManageSolverPropertyEditButtons"); // NOI18N

        buttonSaveSolverProperty.setText(resourceMap.getString("buttonSaveSolverProperty.text")); // NOI18N
        buttonSaveSolverProperty.setEnabled(false);
        buttonSaveSolverProperty.setName("buttonSaveSolverProperty"); // NOI18N

        javax.swing.GroupLayout panelManageSolverPropertyEditButtonsLayout = new javax.swing.GroupLayout(panelManageSolverPropertyEditButtons);
        panelManageSolverPropertyEditButtons.setLayout(panelManageSolverPropertyEditButtonsLayout);
        panelManageSolverPropertyEditButtonsLayout.setHorizontalGroup(
            panelManageSolverPropertyEditButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyEditButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonSaveSolverProperty)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        panelManageSolverPropertyEditButtonsLayout.setVerticalGroup(
            panelManageSolverPropertyEditButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonSaveSolverProperty)
        );

        panelManageSolverPropertyEditInput.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelManageSolverPropertyEditInput.setName("panelManageSolverPropertyEditInput"); // NOI18N

        textSolverPropertyFieldName.setText(resourceMap.getString("textSolverPropertyFieldName.text")); // NOI18N
        textSolverPropertyFieldName.setEnabled(false);
        textSolverPropertyFieldName.setName("textSolverPropertyFieldName"); // NOI18N

        labelSolverPropertyname.setText(resourceMap.getString("labelSolverPropertyname.text")); // NOI18N
        labelSolverPropertyname.setName("labelSolverPropertyname"); // NOI18N

        textSolvertPropertyFieldPrefix.setText(resourceMap.getString("textSolvertPropertyFieldPrefix.text")); // NOI18N
        textSolvertPropertyFieldPrefix.setEnabled(false);
        textSolvertPropertyFieldPrefix.setName("textSolvertPropertyFieldPrefix"); // NOI18N

        labelSolverPropertyPrefix.setText(resourceMap.getString("labelSolverPropertyPrefix.text")); // NOI18N
        labelSolverPropertyPrefix.setName("labelSolverPropertyPrefix"); // NOI18N

        jScrollPane1.setEnabled(false);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        textAreaResultPropertyDescription.setColumns(20);
        textAreaResultPropertyDescription.setRows(4);
        textAreaResultPropertyDescription.setWrapStyleWord(true);
        textAreaResultPropertyDescription.setEnabled(false);
        textAreaResultPropertyDescription.setName("textAreaResultPropertyDescription"); // NOI18N
        jScrollPane1.setViewportView(textAreaResultPropertyDescription);

        labelSolverPropertyDescription.setText(resourceMap.getString("labelSolverPropertyDescription.text")); // NOI18N
        labelSolverPropertyDescription.setName("labelSolverPropertyDescription"); // NOI18N

        comboBoxSolverPropertyValuetype.setEnabled(false);
        comboBoxSolverPropertyValuetype.setName("comboBoxSolverPropertyValuetype"); // NOI18N

        labelSolverPropertyValuetype.setText(resourceMap.getString("labelSolverPropertyValuetype.text")); // NOI18N
        labelSolverPropertyValuetype.setName("labelSolverPropertyValuetype"); // NOI18N

        buttonSolverPropertyAddValueType.setText(resourceMap.getString("buttonSolverPropertyAddValueType.text")); // NOI18N
        buttonSolverPropertyAddValueType.setEnabled(false);
        buttonSolverPropertyAddValueType.setName("buttonSolverPropertyAddValueType"); // NOI18N

        labeSolverPropertyType.setText(resourceMap.getString("labeSolverPropertyType.text")); // NOI18N
        labeSolverPropertyType.setName("labeSolverPropertyType"); // NOI18N

        comboBoxSolverPropertyType.setEnabled(false);
        comboBoxSolverPropertyType.setName("comboBoxSolverPropertyType"); // NOI18N

        javax.swing.GroupLayout panelManageSolverPropertyEditInputLayout = new javax.swing.GroupLayout(panelManageSolverPropertyEditInput);
        panelManageSolverPropertyEditInput.setLayout(panelManageSolverPropertyEditInputLayout);
        panelManageSolverPropertyEditInputLayout.setHorizontalGroup(
            panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                        .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSolverPropertyPrefix)
                            .addComponent(labelSolverPropertyname)
                            .addComponent(labelSolverPropertyDescription))
                        .addGap(71, 71, 71)
                        .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                            .addComponent(textSolvertPropertyFieldPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                            .addComponent(textSolverPropertyFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)))
                    .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                        .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                                .addComponent(labeSolverPropertyType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBoxSolverPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                                .addComponent(labelSolverPropertyValuetype)
                                .addGap(71, 71, 71)
                                .addComponent(comboBoxSolverPropertyValuetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonSolverPropertyAddValueType)))
                .addContainerGap())
        );
        panelManageSolverPropertyEditInputLayout.setVerticalGroup(
            panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                        .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSolverPropertyname)
                            .addComponent(textSolverPropertyFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSolvertPropertyFieldPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelManageSolverPropertyEditInputLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelSolverPropertyPrefix)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSolverPropertyDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSolverPropertyValuetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSolverPropertyValuetype)
                    .addComponent(buttonSolverPropertyAddValueType))
                .addGap(18, 18, 18)
                .addGroup(panelManageSolverPropertyEditInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeSolverPropertyType)
                    .addComponent(comboBoxSolverPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelManageSolverPropertyEditLayout = new javax.swing.GroupLayout(panelManageSolverPropertyEdit);
        panelManageSolverPropertyEdit.setLayout(panelManageSolverPropertyEditLayout);
        panelManageSolverPropertyEditLayout.setHorizontalGroup(
            panelManageSolverPropertyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManageSolverPropertyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelManageSolverPropertyEditInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelManageSolverPropertyEditButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelManageSolverPropertyEditLayout.setVerticalGroup(
            panelManageSolverPropertyEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelManageSolverPropertyEditInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelManageSolverPropertyEditButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jSplitPane1.setRightComponent(panelManageSolverPropertyEdit);

        javax.swing.GroupLayout panelManageSolverPropertyLayout = new javax.swing.GroupLayout(panelManageSolverProperty);
        panelManageSolverProperty.setLayout(panelManageSolverPropertyLayout);
        panelManageSolverPropertyLayout.setHorizontalGroup(
            panelManageSolverPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManageSolverPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelManageSolverPropertyLayout.setVerticalGroup(
            panelManageSolverPropertyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManageSolverPropertyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        managePropertyPane.addTab(resourceMap.getString("panelManageSolverProperty.TabConstraints.tabTitle"), panelManageSolverProperty); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managePropertyPane, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managePropertyPane, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewSolverPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewSolverPropertyActionPerformed
        manageSolverProperties.NewSolverProperty();
    }//GEN-LAST:event_buttonNewSolverPropertyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNewSolverProperty;
    private javax.swing.JButton buttonRemoveSolverProperty;
    private javax.swing.JButton buttonSaveSolverProperty;
    private javax.swing.JButton buttonSolverPropertyAddValueType;
    private javax.swing.JComboBox comboBoxSolverPropertyType;
    private javax.swing.JComboBox comboBoxSolverPropertyValuetype;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labeSolverPropertyType;
    private javax.swing.JLabel labelSolverPropertyDescription;
    private javax.swing.JLabel labelSolverPropertyPrefix;
    private javax.swing.JLabel labelSolverPropertyValuetype;
    private javax.swing.JLabel labelSolverPropertyname;
    private javax.swing.JTabbedPane managePropertyPane;
    private javax.swing.JPanel panelManageSolverProperty;
    private javax.swing.JPanel panelManageSolverPropertyEdit;
    private javax.swing.JPanel panelManageSolverPropertyEditButtons;
    private javax.swing.JPanel panelManageSolverPropertyEditInput;
    private javax.swing.JPanel panelManageSolverPropertyShowButtons;
    private javax.swing.JScrollPane panelManageSolverPropertyTable;
    private javax.swing.JPanel panelMangeSolverPropertyShow;
    private javax.swing.JTable tableSovlerProperty;
    private javax.swing.JTextArea textAreaResultPropertyDescription;
    private javax.swing.JTextField textSolverPropertyFieldName;
    private javax.swing.JTextField textSolvertPropertyFieldPrefix;
    // End of variables declaration//GEN-END:variables

    public void enableSolverPropertyEditField(boolean enable) {
            this.comboBoxSolverPropertyType.setEnabled(enable);
            this.comboBoxSolverPropertyValuetype.setEnabled(enable);
            this.buttonSolverPropertyAddValueType.setEnabled(enable);
            this.buttonSaveSolverProperty.setEnabled(enable);
            this.textSolvertPropertyFieldPrefix.setEnabled(enable);
            this.textSolverPropertyFieldName.setEnabled(enable);
            this.textAreaResultPropertyDescription.setEnabled(enable);

    }

    public void clearSolverPropertyEditField() {
        this.comboBoxSolverPropertyType.setSelectedIndex(0);
        this.comboBoxSolverPropertyValuetype.setSelectedIndex(0);
        this.textSolverPropertyFieldName.setText("");
        this.textSolvertPropertyFieldPrefix.setText("");
        this.textAreaResultPropertyDescription.setText("");
    }

}
