/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCManageGridQueuesDialog.java
 *
 * Created on 11.05.2010, 16:13:30
 */

package edacc;

import edacc.gridqueues.GridQueuesController;
import edacc.gridqueues.QueueListModel;
import edacc.model.GridQueue;
import edacc.model.GridQueueDAO;
import edacc.model.NoConnectionToDBException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dgall
 */
public class EDACCManageGridQueuesDialog extends javax.swing.JDialog {

    private EDACCGridSettingsView gridSettings;

    /** Creates new form EDACCManageGridQueuesDialog */
    public EDACCManageGridQueuesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        gridSettings = new EDACCGridSettingsView(parent, true, this);
        initComponents();
        try {
            listQueues.setModel(new QueueListModel());
        } catch (NoConnectionToDBException ex) {
            JOptionPane.showMessageDialog(this, "You have to establish a connection to the database first!", "Error!", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "A database error occured while loading the dialog: " + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQueues = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listQueues = new javax.swing.JList();
        lblChosenQueue = new javax.swing.JLabel();
        btnCreateQueue = new javax.swing.JButton();
        btnEditQueue = new javax.swing.JButton();
        btnChooseQueue = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRemoveQueue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCManageGridQueuesDialog.class);
        setTitle(resourceMap.getString("dlgManageQueues.title")); // NOI18N
        setName("dlgManageQueues"); // NOI18N

        lblQueues.setText(resourceMap.getString("lblQueues.text")); // NOI18N
        lblQueues.setName("lblQueues"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listQueues.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listQueues.setName("listQueues"); // NOI18N
        jScrollPane1.setViewportView(listQueues);

        lblChosenQueue.setText(resourceMap.getString("lblChosenQueue.text")); // NOI18N
        lblChosenQueue.setName("lblChosenQueue"); // NOI18N

        btnCreateQueue.setLabel(resourceMap.getString("btnCreateQueue.label")); // NOI18N
        btnCreateQueue.setName("btnCreateQueue"); // NOI18N
        btnCreateQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateQueue(evt);
            }
        });

        btnEditQueue.setLabel(resourceMap.getString("btnEditQueue.label")); // NOI18N
        btnEditQueue.setName("btnEditQueue"); // NOI18N
        btnEditQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditQueue(evt);
            }
        });

        btnChooseQueue.setLabel(resourceMap.getString("btnChooseQueue.label")); // NOI18N
        btnChooseQueue.setName("btnChooseQueue"); // NOI18N
        btnChooseQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseQueue(evt);
            }
        });

        btnCancel.setLabel(resourceMap.getString("btnCancel.label")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel(evt);
            }
        });

        btnRemoveQueue.setText(resourceMap.getString("btnRemoveQueue.text")); // NOI18N
        btnRemoveQueue.setName("btnRemoveQueue"); // NOI18N
        btnRemoveQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveQueue(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(lblQueues)
                    .addComponent(lblChosenQueue)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveQueue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChooseQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQueues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChosenQueue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateQueue)
                    .addComponent(btnEditQueue)
                    .addComponent(btnCancel)
                    .addComponent(btnChooseQueue)
                    .addComponent(btnRemoveQueue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblQueues.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateQueue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateQueue
        try {
            gridSettings.loadSettings(null);
            gridSettings.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot show create dialog: " + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateQueue

    private void btnEditQueue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditQueue
        GridQueue selected = (GridQueue) listQueues.getSelectedValue();
        if (selected == null)
            return;
        try {
            gridSettings.loadSettings(selected);
            gridSettings.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot show edit dialog: " + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditQueue

    private void btnChooseQueue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseQueue
        GridQueue selected = (GridQueue) listQueues.getSelectedValue();
        if (selected == null)
            return;
        GridQueuesController.getInstance().setChosenQueue(selected);
        lblChosenQueue.setText("Chosen queue: " + selected.getName());
    }//GEN-LAST:event_btnChooseQueue

    private void btnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel
        this.setVisible(false);
    }//GEN-LAST:event_btnCancel

    private void btnRemoveQueue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveQueue
        GridQueue selected = (GridQueue) listQueues.getSelectedValue();
        if (selected == null)
            return;
        try {
            GridQueueDAO.remove(selected);
            refreshView();
        } catch (NoConnectionToDBException ex) {
            JOptionPane.showMessageDialog(this, "You have to establish a connection to the database first!", "Error!", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "An error occured while removing the queue from database: " + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveQueue

    public void refreshView() throws NoConnectionToDBException, SQLException {
        // refresh list
        ((QueueListModel) listQueues.getModel()).refreshQueues();
        // refresh "chosen queue" text
        GridQueue selected = GridQueuesController.getInstance().getChosenQueue();
        if (selected == null)
            lblChosenQueue.setText("Chosen queue: none");
        else
            lblChosenQueue.setText("Chosen queue: " + selected.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseQueue;
    private javax.swing.JButton btnCreateQueue;
    private javax.swing.JButton btnEditQueue;
    private javax.swing.JButton btnRemoveQueue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChosenQueue;
    private javax.swing.JLabel lblQueues;
    private javax.swing.JList listQueues;
    // End of variables declaration//GEN-END:variables

}
