/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCInstanceGeneratorUnifKCNF.java
 *
 * Created on 14.12.2010, 15:23:12
 */
package edacc;

import edacc.model.InstanceClass;
import edacc.model.InstanceClassAlreadyInDBException;
import edacc.model.InstanceClassDAO;
import edacc.model.NoConnectionToDBException;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;
import edacc.model.instanceGeneratorUnifKCNFController;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author balint
 */
public class EDACCInstanceGeneratorUnifKCNF extends javax.swing.JDialog {

    private InstanceClass parentClass;

    /** Creates new form EDACCInstanceGeneratorUnifKCNF */
    public EDACCInstanceGeneratorUnifKCNF(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        this.setTitle("Genrate uniform random k-SAT Formulas");
        this.setResizable(false);
        initComponents();
        this.cbSeries.setSelected(false);
        this.jLabel2.setEnabled(false);
        this.tfVStep.setEnabled(false);
        this.jLabel3.setEnabled(false);
        this.tfVStop.setEnabled(false);
        this.tfNV.setText("1");
        this.lbParentClass.setText("");



        //Nur zahlen möglich und nur positive
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfVStart = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfVStep = new javax.swing.JTextField();
        tfVStop = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        tfR = new javax.swing.JFormattedTextField(DecimalFormat.getNumberInstance(Locale.ENGLISH));
        btnGenerate = new javax.swing.JButton();
        cbGC = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbSeries = new javax.swing.JCheckBox();
        btSelParClass = new javax.swing.JButton();
        lbParentClass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        tfVStart.setName("tfVStart"); // NOI18N
        tfVStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVStartKeyReleased(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCInstanceGeneratorUnifKCNF.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        tfVStep.setName("tfVStep"); // NOI18N
        tfVStep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVStepKeyReleased(evt);
            }
        });

        tfVStop.setName("tfVStop"); // NOI18N
        tfVStop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVStopKeyReleased(evt);
            }
        });

        btnCancel.setLabel(resourceMap.getString("btnCancel.label")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tfR.setName("tfR"); // NOI18N
        tfR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRKeyReleased(evt);
            }
        });

        btnGenerate.setLabel(resourceMap.getString("btnGenerate.label")); // NOI18N
        btnGenerate.setName("btnGenerate"); // NOI18N
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        cbGC.setText(resourceMap.getString("cbGC.text")); // NOI18N
        cbGC.setName("cbGC"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        tfNV.setName("tfNV"); // NOI18N
        tfNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNVKeyReleased(evt);
            }
        });

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        tfK.setName("tfK"); // NOI18N
        tfK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfKKeyReleased(evt);
            }
        });

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        cbSeries.setText(resourceMap.getString("cbSeries.text")); // NOI18N
        cbSeries.setName("cbSeries"); // NOI18N
        cbSeries.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbSeriesStateChanged(evt);
            }
        });

        btSelParClass.setText(resourceMap.getString("btSelParClass.text")); // NOI18N
        btSelParClass.setName("btSelParClass"); // NOI18N
        btSelParClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelParClassActionPerformed(evt);
            }
        });

        lbParentClass.setFont(resourceMap.getFont("lbParentClass.font")); // NOI18N
        lbParentClass.setText(resourceMap.getString("lbParentClass.text")); // NOI18N
        lbParentClass.setFocusable(false);
        lbParentClass.setName("lbParentClass"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfVStep, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfVStop, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfNV, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfVStart, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfR, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(tfK, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbSeries)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cbGC, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSelParClass)
                        .addGap(18, 18, 18)
                        .addComponent(lbParentClass, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(tfK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(tfR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(tfVStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSeries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfVStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(tfVStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(tfNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(cbGC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelParClass)
                    .addComponent(lbParentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getClauseLength() {
        return Integer.parseInt(this.tfK.getText());
    }

    public float getRatio() {
        return Float.parseFloat(this.tfR.getText());
    }

    public int getNumVariables() {
        return Integer.parseInt(this.tfVStart.getText());
    }

    public boolean getGenerateSeries() {
        return this.cbSeries.isSelected();
    }

    public int getSteppingSeries() {
        return Integer.parseInt(this.tfVStep.getText());
    }

    public int getStopSeries() {
        return Integer.parseInt(this.tfVStop.getText());
    }

    public int getNumInstances() {
        return Integer.parseInt(this.tfNV.getText());
    }

    public boolean getGenerateClasses() {
        return this.cbGC.isSelected();
    }

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        instanceGeneratorUnifKCNFController controller = new instanceGeneratorUnifKCNFController();
        String message = "";
        boolean itemsMissing = false;
        int k, n, step, stop, num;
        double r;
        boolean series, genClass;
        if (this.tfK.getText().isEmpty()) {
            message += "\"Maximum clause length\" \n";
            itemsMissing = true;
        }
        if (this.tfR.getText().isEmpty()) {
            message += "\"Ratio\" \n";
            itemsMissing = true;
        }
        if (this.tfVStart.getText().isEmpty()) {
            message += "\"Number of variables\" \n";
            itemsMissing = true;
        }
        if (itemsMissing) {
            message = "Please provide values for the following fields:\n" + message;
        }
        if ((this.cbSeries.isSelected()) && (!this.tfVStep.getText().isEmpty() && !this.tfVStart.getText().isEmpty() && this.tfVStop.getText().isEmpty())) {
            message += "You have specified a start value for the number of variables and a step!\n";
            message += "Please provide also the \"stop at\" value!";
            itemsMissing = true;
        }

        if (itemsMissing) {
            JOptionPane.showMessageDialog(this.getParent(),
                    message,
                    "Missing specifications!",
                    JOptionPane.WARNING_MESSAGE);
        } else if ((this.cbSeries.isSelected()) && (Integer.parseInt(this.tfVStop.getText()) < Integer.parseInt(this.tfVStart.getText()))) {
            JOptionPane.showMessageDialog(this.getParent(),
                    "Start value for the number of variables is larger than stop value",
                    "Number of variables range error",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            //hier müssen alle parse-fehler noch abgefangen werden!!!!
            try {
                k = Integer.parseInt(this.tfK.getText());
                n = Integer.parseInt(this.tfVStart.getText());
                num = Integer.parseInt(this.tfNV.getText());
                //r = Double.parseDouble(this.tfR.getText());
                try {
                    r = DecimalFormat.getNumberInstance(Locale.ENGLISH).parse(tfR.getText()).doubleValue();
                    series = this.cbSeries.isSelected();
                    if (series) {
                        step = Integer.parseInt(this.tfVStep.getText());
                        stop = Integer.parseInt(this.tfVStop.getText());
                    } else {
                        step = n;
                        stop = 1;
                    }
                    genClass = this.cbGC.isSelected();
                    //das muss noch in einer progressbar rein!!!
                    //call Controller to generate and add instances
                    try {
                        controller.generate(k, r, n, series, step, stop, num, genClass, this.parentClass);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this,
                                "There is a Problem with the database: " + ex.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    } catch (InstanceClassAlreadyInDBException ex) {
                        JOptionPane.showMessageDialog(this,
                                "Instance class is already in the system.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }

                    this.setVisible(false);
                } catch (ParseException ex) {
                    Logger.getLogger(EDACCInstanceGeneratorUnifKCNF.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this.getParent(),
                            "Values specified for ratio is invalid!",
                            "Invalid values specified!",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this.getParent(),
                        "Values specified are invalid!" + ex.getMessage(),
                        "Invalid values specified!",
                        JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private String getNumberText(String text) {
        String res = "";
        int begin;
        for (begin = 0; begin < text.length() && text.charAt(begin) == '0'; begin++);
        if (begin > 0 && begin == text.length()) {
            return "";
        }
        for (int i = begin; i < text.length(); i++) {
            if (text.charAt(i) >= '0' && text.charAt(i) <= '9') {
                res += text.charAt(i);
            }
        }
        return res;
    }
    private void tfKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKKeyReleased
        int ss = tfK.getSelectionStart();
        int se = tfK.getSelectionEnd();
        int dot = tfK.getCaret().getDot();
        tfK.setText(this.getNumberText(tfK.getText()));
        tfK.getCaret().setDot(dot);
        tfK.setSelectionStart(ss);
        tfK.setSelectionEnd(se);
    }//GEN-LAST:event_tfKKeyReleased

    private void tfRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRKeyReleased
        /*int ss = tfR.getSelectionStart();
        int se = tfR.getSelectionEnd();
        int dot = tfR.getCaret().getDot();
        tfR.setText(EDACCExperimentMode.getNumberText(tfR.getText()));
        tfR.getCaret().setDot(dot);
        tfR.setSelectionStart(ss);
        tfR.setSelectionEnd(se);*/
    }//GEN-LAST:event_tfRKeyReleased

    private void tfVStartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVStartKeyReleased
        int ss = tfVStart.getSelectionStart();
        int se = tfVStart.getSelectionEnd();
        int dot = tfVStart.getCaret().getDot();
        tfVStart.setText(this.getNumberText(tfVStart.getText()));
        tfVStart.getCaret().setDot(dot);
        tfVStart.setSelectionStart(ss);
        tfVStart.setSelectionEnd(se);
    }//GEN-LAST:event_tfVStartKeyReleased

    private void tfVStepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVStepKeyReleased
        int ss = tfVStep.getSelectionStart();
        int se = tfVStep.getSelectionEnd();
        int dot = tfVStep.getCaret().getDot();
        tfVStep.setText(this.getNumberText(tfVStep.getText()));
        tfVStep.getCaret().setDot(dot);
        tfVStep.setSelectionStart(ss);
        tfVStep.setSelectionEnd(se);
    }//GEN-LAST:event_tfVStepKeyReleased

    private void tfVStopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfVStopKeyReleased
        int ss = tfVStop.getSelectionStart();
        int se = tfVStop.getSelectionEnd();
        int dot = tfVStop.getCaret().getDot();
        tfVStop.setText(this.getNumberText(tfVStop.getText()));
        tfVStop.getCaret().setDot(dot);
        tfVStop.setSelectionStart(ss);
        tfVStop.setSelectionEnd(se);
    }//GEN-LAST:event_tfVStopKeyReleased

    private void tfNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNVKeyReleased
        int ss = tfNV.getSelectionStart();
        int se = tfNV.getSelectionEnd();
        int dot = tfNV.getCaret().getDot();
        tfNV.setText(this.getNumberText(tfNV.getText()));
        tfNV.getCaret().setDot(dot);
        tfNV.setSelectionStart(ss);
        tfNV.setSelectionEnd(se);
    }//GEN-LAST:event_tfNVKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbSeriesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbSeriesStateChanged
        this.tfVStep.setEnabled(cbSeries.isSelected());
        this.tfVStop.setEnabled(cbSeries.isSelected());
        this.jLabel2.setEnabled(cbSeries.isSelected());
        this.jLabel3.setEnabled(cbSeries.isSelected());
    }//GEN-LAST:event_cbSeriesStateChanged

    private void btSelParClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelParClassActionPerformed
        try {
            EDACCSelectParentInstanceClassDialog selectParent = new EDACCSelectParentInstanceClassDialog(EDACCApp.getApplication().getMainFrame(), true, new DefaultTreeModel(InstanceClassDAO.getAllAsTree()));
            selectParent.setLocationRelativeTo(this);
            selectParent.setAlwaysOnTop(true);
            selectParent.initialize();
            selectParent.setVisible(true);
            if (selectParent.getInstanceClassParent() != null) {
                parentClass = selectParent.getInstanceClassParent();
                this.lbParentClass.setText(parentClass.getName());
            } else {
                this.lbParentClass.setText("");
            }

        } catch (NoConnectionToDBException ex) {
            Logger.getLogger(EDACCCreateEditInstanceClassDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EDACCCreateEditInstanceClassDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSelParClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EDACCInstanceGeneratorUnifKCNF dialog = new EDACCInstanceGeneratorUnifKCNF(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelParClass;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JCheckBox cbGC;
    private javax.swing.JCheckBox cbSeries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbParentClass;
    private javax.swing.JTextField tfK;
    private javax.swing.JTextField tfNV;
    private javax.swing.JTextField tfR;
    private javax.swing.JTextField tfVStart;
    private javax.swing.JTextField tfVStep;
    private javax.swing.JTextField tfVStop;
    // End of variables declaration//GEN-END:variables
}
