/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EDACCAddInstanceToInstanceClass.java
 *
 * Created on 22.03.2010, 17:22:57
 */

package edacc;

import edacc.manageDB.AddInstanceToInstanceSourceClassTreeSelectionListener;
import edacc.manageDB.AddInstanceToInstanceUserClassTreeSelectionListener;
import edacc.model.InstanceClass;
import edacc.model.InstanceClassDAO;
import edacc.model.NoConnectionToDBException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author rretz
 */
public class EDACCAddInstanceToInstanceClass extends javax.swing.JDialog {
    InstanceClass input;
    /** Creates new form EDACCAddInstanceToInstanceClass */
    public EDACCAddInstanceToInstanceClass(java.awt.Frame parent, boolean modal) throws NoConnectionToDBException, SQLException {
        super(parent, modal);
        initComponents();
        //Initiate the instance source class tree
        jTreeSourceClass.setModel(InstanceClassDAO.getSourceAsTree());
        jTreeSourceClass.setRootVisible(false);
        jTreeSourceClass.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        jTreeSourceClass.addTreeSelectionListener(new AddInstanceToInstanceSourceClassTreeSelectionListener(this));
        jTreeSourceClass.setRootVisible(false);
        //Initiate the instance source class table

        jTreeUserClass.setModel(InstanceClassDAO.getUserClassAsTree());
        jTreeUserClass.setRootVisible(false);
        jTreeUserClass.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        jTreeUserClass.addTreeSelectionListener(new AddInstanceToInstanceUserClassTreeSelectionListener(this));
        jTreeUserClass.setRootVisible(false);
    }

    public InstanceClass getInput(){
        return input;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSourceOrUser = new javax.swing.ButtonGroup();
        jRadioButtonSourceClass = new javax.swing.JRadioButton();
        jRadioButtonUserClass = new javax.swing.JRadioButton();
        jPanelButton = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeSourceClass = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeUserClass = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCAddInstanceToInstanceClass.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(350, 500));
        setModal(true);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        buttonGroupSourceOrUser.add(jRadioButtonSourceClass);
        jRadioButtonSourceClass.setText(resourceMap.getString("jRadioButtonSourceClass.text")); // NOI18N
        jRadioButtonSourceClass.setToolTipText(resourceMap.getString("jRadioButtonSourceClass.toolTipText")); // NOI18N
        jRadioButtonSourceClass.setName("jRadioButtonSourceClass"); // NOI18N

        buttonGroupSourceOrUser.add(jRadioButtonUserClass);
        jRadioButtonUserClass.setText(resourceMap.getString("jRadioButtonUserClass.text")); // NOI18N
        jRadioButtonUserClass.setToolTipText(resourceMap.getString("jRadioButtonUserClass.toolTipText")); // NOI18N
        jRadioButtonUserClass.setName("jRadioButtonUserClass"); // NOI18N

        jPanelButton.setName("jPanelButton"); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setToolTipText(resourceMap.getString("jButtonCancel.toolTipText")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setToolTipText(resourceMap.getString("jButtonOk.toolTipText")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonLayout = new javax.swing.GroupLayout(jPanelButton);
        jPanelButton.setLayout(jPanelButtonLayout);
        jPanelButtonLayout.setHorizontalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLayout.createSequentialGroup()
                .addComponent(jButtonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jButtonCancel))
        );

        jPanelButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancel, jButtonOk});

        jPanelButtonLayout.setVerticalGroup(
            jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk)))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTreeSourceClass.setName("jTreeSourceClass"); // NOI18N
        jScrollPane1.setViewportView(jTreeSourceClass);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTreeUserClass.setName("jTreeUserClass"); // NOI18N
        jScrollPane2.setViewportView(jTreeUserClass);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jRadioButtonUserClass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addComponent(jRadioButtonSourceClass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonSourceClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonUserClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        input = new InstanceClass();
        if(buttonGroupSourceOrUser.getSelection() == null){
            JOptionPane.showMessageDialog(this,
                    "Please choose if the instance source class has to be changed or a new " +
                    "instance user class has to be added." ,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            if(jRadioButtonSourceClass.isSelected()){
                if(jTreeSourceClass.getSelectionCount() == 0){
                    JOptionPane.showMessageDialog(this,
                    "Please select one of the instance source classes from the tree",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                }else{
                    input = (InstanceClass) ((DefaultMutableTreeNode)jTreeSourceClass.getSelectionPath().getLastPathComponent()).getUserObject();
                    this.setVisible(false);
                }
            }else{
                if(jTreeUserClass.getSelectionCount() == 0){
                    JOptionPane.showMessageDialog(this,
                    "Please select one of the instance user classes from the table",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                }else{
                    input = (InstanceClass) ((DefaultMutableTreeNode)jTreeUserClass.getSelectionPath().getLastPathComponent()).getUserObject();
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        input = null;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            jTreeSourceClass.setModel(InstanceClassDAO.getSourceAsTree());
            jTreeUserClass.setModel(InstanceClassDAO.getUserClassAsTree());
         } catch (NoConnectionToDBException ex) {
            JOptionPane.showMessageDialog(this.rootPane,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this.rootPane,
                    "There is a Problem with the database: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSourceOrUser;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JRadioButton jRadioButtonSourceClass;
    private javax.swing.JRadioButton jRadioButtonUserClass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTreeSourceClass;
    private javax.swing.JTree jTreeUserClass;
    // End of variables declaration//GEN-END:variables

    public void selectUserClass() {
        jRadioButtonUserClass.setSelected(true);
    }

    public void selectSourceClass() {
        jRadioButtonSourceClass.setSelected(true);
    }

}
