/*
 * EDACCView.java
 */

package edacc;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import edacc.experiment.*;
import java.util.Locale;

/**
 * The application's main frame.
 */
public class EDACCView extends FrameView {
    public ExperimentController expController;
    public ExperimentTableModel expTableModel;
    public InstanceTableModel insTableModel;

    public EDACCView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });

        manageExperimentPane.setEnabledAt(1, false);
        manageExperimentPane.setEnabledAt(2, false);
        manageExperimentPane.setEnabledAt(3, false);

        expController = new ExperimentController(this);
        expTableModel = new ExperimentTableModel();
        insTableModel = new InstanceTableModel();
        tableExperiments.setModel(expTableModel);
        tableInstances.setModel(insTableModel);
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = EDACCApp.getApplication().getMainFrame();
            aboutBox = new EDACCAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        EDACCApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        manageExperimentPane = new javax.swing.JTabbedPane();
        panelManageExperiment = new javax.swing.JPanel();
        scrollPaneExperimentsTable = new javax.swing.JScrollPane();
        tableExperiments = new javax.swing.JTable();
        btnRemoveExperiment = new javax.swing.JButton();
        btnLoadExperiment = new javax.swing.JButton();
        pnlNewExperiment = new javax.swing.JPanel();
        lblExperimentName = new javax.swing.JLabel();
        lblExperimentDate = new javax.swing.JLabel();
        lblExperimentDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExperimentDescription = new javax.swing.JTextArea();
        txtExperimentName = new javax.swing.JTextField();
        txtExperimentDate = new javax.swing.JTextField();
        btnCreateExperiment = new javax.swing.JButton();
        panelChooseSolver = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelChooseInstances = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInstances = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        panelExperimentParams = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        connectToDBMenuItem = new javax.swing.JMenuItem();
        generateDBMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        gridMenu = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenuItem();
        modusMenu = new javax.swing.JMenu();
        mangeDBMenuItem = new javax.swing.JRadioButtonMenuItem();
        manageExperimentMenuItem = new javax.swing.JRadioButtonMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        manageExperimentPane.setName("manageExperimentPane"); // NOI18N

        panelManageExperiment.setName("panelManageExperiment"); // NOI18N

        scrollPaneExperimentsTable.setName("scrollPaneExperimentsTable"); // NOI18N

        tableExperiments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableExperiments.setName("tableExperiments"); // NOI18N
        scrollPaneExperimentsTable.setViewportView(tableExperiments);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(EDACCView.class);
        btnRemoveExperiment.setText(resourceMap.getString("btnRemoveExperiment.text")); // NOI18N
        btnRemoveExperiment.setName("btnRemoveExperiment"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getActionMap(EDACCView.class, this);
        btnLoadExperiment.setAction(actionMap.get("btnLoadExperiment")); // NOI18N
        btnLoadExperiment.setText(resourceMap.getString("btnLoadExperiment.text")); // NOI18N
        btnLoadExperiment.setName("btnLoadExperiment"); // NOI18N

        pnlNewExperiment.setBorder(javax.swing.BorderFactory.createTitledBorder("New Experiment"));
        pnlNewExperiment.setName("pnlNewExperiment"); // NOI18N

        lblExperimentName.setText(resourceMap.getString("lblExperimentName.text")); // NOI18N
        lblExperimentName.setName("lblExperimentName"); // NOI18N

        lblExperimentDate.setText(resourceMap.getString("lblExperimentDate.text")); // NOI18N
        lblExperimentDate.setName("lblExperimentDate"); // NOI18N

        lblExperimentDescription.setText(resourceMap.getString("lblExperimentDescription.text")); // NOI18N
        lblExperimentDescription.setName("lblExperimentDescription"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtExperimentDescription.setColumns(20);
        txtExperimentDescription.setRows(5);
        txtExperimentDescription.setName("txtExperimentDescription"); // NOI18N
        jScrollPane1.setViewportView(txtExperimentDescription);

        txtExperimentName.setName("txtExperimentName"); // NOI18N

        txtExperimentDate.setName("txtExperimentDate"); // NOI18N

        btnCreateExperiment.setText(resourceMap.getString("btnCreateExperiment.text")); // NOI18N
        btnCreateExperiment.setName("btnCreateExperiment"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlNewExperimentLayout = new org.jdesktop.layout.GroupLayout(pnlNewExperiment);
        pnlNewExperiment.setLayout(pnlNewExperimentLayout);
        pnlNewExperimentLayout.setHorizontalGroup(
            pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlNewExperimentLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblExperimentDate)
                    .add(lblExperimentName)
                    .add(lblExperimentDescription))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtExperimentName)
                    .add(txtExperimentDate)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .add(12, 12, 12)
                .add(btnCreateExperiment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNewExperimentLayout.setVerticalGroup(
            pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlNewExperimentLayout.createSequentialGroup()
                .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnlNewExperimentLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnCreateExperiment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlNewExperimentLayout.createSequentialGroup()
                        .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtExperimentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblExperimentName))
                        .add(8, 8, 8)
                        .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtExperimentDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblExperimentDate))
                        .add(10, 10, 10)
                        .add(pnlNewExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblExperimentDescription)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout panelManageExperimentLayout = new org.jdesktop.layout.GroupLayout(panelManageExperiment);
        panelManageExperiment.setLayout(panelManageExperimentLayout);
        panelManageExperimentLayout.setHorizontalGroup(
            panelManageExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelManageExperimentLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelManageExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scrollPaneExperimentsTable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .add(panelManageExperimentLayout.createSequentialGroup()
                        .add(pnlNewExperiment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                        .add(btnRemoveExperiment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnLoadExperiment, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelManageExperimentLayout.setVerticalGroup(
            panelManageExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelManageExperimentLayout.createSequentialGroup()
                .addContainerGap()
                .add(scrollPaneExperimentsTable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 344, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelManageExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlNewExperiment, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelManageExperimentLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnLoadExperiment)
                        .add(btnRemoveExperiment)))
                .addContainerGap())
        );

        manageExperimentPane.addTab("Experiments", panelManageExperiment);

        panelChooseSolver.setName("panelChooseSolver"); // NOI18N

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N

        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N

        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jButton8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButton9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 260, Short.MAX_VALUE)
                        .add(jButton10))
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 373, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton10)
                    .add(jButton8)
                    .add(jButton9))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 429, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel3);

        org.jdesktop.layout.GroupLayout panelChooseSolverLayout = new org.jdesktop.layout.GroupLayout(panelChooseSolver);
        panelChooseSolver.setLayout(panelChooseSolverLayout);
        panelChooseSolverLayout.setHorizontalGroup(
            panelChooseSolverLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelChooseSolverLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelChooseSolverLayout.setVerticalGroup(
            panelChooseSolverLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelChooseSolverLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 490, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        manageExperimentPane.addTab("Solvers", panelChooseSolver);

        panelChooseInstances.setName("panelChooseInstances"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tableInstances.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableInstances.setName("tableInstances"); // NOI18N
        jScrollPane2.setViewportView(tableInstances);

        jButton3.setName("jButton3"); // NOI18N

        jButton4.setName("jButton4"); // NOI18N

        jButton5.setName("jButton5"); // NOI18N

        jButton6.setName("jButton6"); // NOI18N

        jButton7.setName("jButton7"); // NOI18N

        org.jdesktop.layout.GroupLayout panelChooseInstancesLayout = new org.jdesktop.layout.GroupLayout(panelChooseInstances);
        panelChooseInstances.setLayout(panelChooseInstancesLayout);
        panelChooseInstancesLayout.setHorizontalGroup(
            panelChooseInstancesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelChooseInstancesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelChooseInstancesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .add(panelChooseInstancesLayout.createSequentialGroup()
                        .add(jButton4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 787, Short.MAX_VALUE)
                        .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelChooseInstancesLayout.setVerticalGroup(
            panelChooseInstancesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelChooseInstancesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 459, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelChooseInstancesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton4)
                    .add(jButton5)
                    .add(jButton6)
                    .add(jButton7))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        manageExperimentPane.addTab("Instances", panelChooseInstances);

        panelExperimentParams.setName("panelExperimentParams"); // NOI18N

        org.jdesktop.layout.GroupLayout panelExperimentParamsLayout = new org.jdesktop.layout.GroupLayout(panelExperimentParams);
        panelExperimentParams.setLayout(panelExperimentParamsLayout);
        panelExperimentParamsLayout.setHorizontalGroup(
            panelExperimentParamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 977, Short.MAX_VALUE)
        );
        panelExperimentParamsLayout.setVerticalGroup(
            panelExperimentParamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 580, Short.MAX_VALUE)
        );

        manageExperimentPane.addTab("Experiment Parameters", panelExperimentParams);

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(manageExperimentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(manageExperimentPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setAutoscrolls(true);
        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        connectToDBMenuItem.setAction(actionMap.get("btnConnectToDB")); // NOI18N
        connectToDBMenuItem.setText(resourceMap.getString("connectToDBMenuItem.text")); // NOI18N
        connectToDBMenuItem.setName("connectToDBMenuItem"); // NOI18N
        fileMenu.add(connectToDBMenuItem);

        generateDBMenuItem.setText(resourceMap.getString("generateDBMenuItem.text")); // NOI18N
        generateDBMenuItem.setName("generateDBMenuItem"); // NOI18N
        fileMenu.add(generateDBMenuItem);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        gridMenu.setName("gridMenu"); // NOI18N

        settingsMenuItem.setName("settingsMenuItem"); // NOI18N
        gridMenu.add(settingsMenuItem);

        menuBar.add(gridMenu);

        modusMenu.setName("modusMenu"); // NOI18N

        mangeDBMenuItem.setSelected(true);
        mangeDBMenuItem.setName("mangeDBMenuItem"); // NOI18N
        modusMenu.add(mangeDBMenuItem);

        manageExperimentMenuItem.setSelected(true);
        manageExperimentMenuItem.setName("manageExperimentMenuItem"); // NOI18N
        modusMenu.add(manageExperimentMenuItem);

        menuBar.add(modusMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
            .add(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 823, Short.MAX_VALUE)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(statusMessageLabel)
                    .add(statusAnimationLabel)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void btnConnectToDB() {
        if (databaseSettings == null) {
            JFrame mainFrame = EDACCApp.getApplication().getMainFrame();
            databaseSettings = new EDACCDatabaseSettingsView(mainFrame, true);
            databaseSettings.setLocationRelativeTo(mainFrame);
        }
        EDACCApp.getApplication().show(databaseSettings);
        expController.initialize();
    }

    @Action
    public void btnLoadExperiment() {
        if (tableExperiments.getSelectedRow() != -1) {
            Integer i = (Integer)expTableModel.getValueAt(tableExperiments.getSelectedRow(), 5);
            expController.loadExperiment(i.intValue());
            manageExperimentPane.setEnabledAt(1, true);
            manageExperimentPane.setEnabledAt(2, true);
            manageExperimentPane.setEnabledAt(3, true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateExperiment;
    private javax.swing.JButton btnLoadExperiment;
    private javax.swing.JButton btnRemoveExperiment;
    private javax.swing.JMenuItem connectToDBMenuItem;
    private javax.swing.JMenuItem generateDBMenuItem;
    private javax.swing.JMenu gridMenu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblExperimentDate;
    private javax.swing.JLabel lblExperimentDescription;
    private javax.swing.JLabel lblExperimentName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButtonMenuItem manageExperimentMenuItem;
    private javax.swing.JTabbedPane manageExperimentPane;
    private javax.swing.JRadioButtonMenuItem mangeDBMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu modusMenu;
    private javax.swing.JPanel panelChooseInstances;
    private javax.swing.JPanel panelChooseSolver;
    private javax.swing.JPanel panelExperimentParams;
    private javax.swing.JPanel panelManageExperiment;
    private javax.swing.JPanel pnlNewExperiment;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollPaneExperimentsTable;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTable tableExperiments;
    private javax.swing.JTable tableInstances;
    private javax.swing.JTextField txtExperimentDate;
    private javax.swing.JTextArea txtExperimentDescription;
    private javax.swing.JTextField txtExperimentName;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
    private JDialog databaseSettings;
}
