/*
 * BooleanFilter.java
 *
 * Created on 12.10.2010, 09:42:14
 */

package edacc.filter;

import javax.swing.ButtonGroup;

/**
 *
 * @author simon
 */
public class BooleanFilter extends javax.swing.JPanel implements FilterInterface {
    ButtonGroup btnGroup;
    /** Creates new form BooleanFilter */
    public BooleanFilter(String name) {
        initComponents();
        btnGroup = new ButtonGroup();
        btnGroup.add(radioTrue);
        btnGroup.add(radioFalse);
        radioTrue.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioTrue = new javax.swing.JRadioButton();
        radioFalse = new javax.swing.JRadioButton();
        chkActivate = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(BooleanFilter.class);
        radioTrue.setText(resourceMap.getString("radioTrue.text")); // NOI18N
        radioTrue.setName("radioTrue"); // NOI18N

        radioFalse.setText(resourceMap.getString("radioFalse.text")); // NOI18N
        radioFalse.setName("radioFalse"); // NOI18N

        chkActivate.setText(resourceMap.getString("chkActivate.text")); // NOI18N
        chkActivate.setName("chkActivate"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(radioTrue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioFalse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(chkActivate))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chkActivate)
                .addComponent(radioTrue)
                .addComponent(radioFalse))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkActivate;
    private javax.swing.JRadioButton radioFalse;
    private javax.swing.JRadioButton radioTrue;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean include(Object value) {
        if (!chkActivate.isSelected()) {
            return true;
        }
        if (value instanceof Boolean) {

            return radioTrue.isSelected() && (Boolean) value || radioFalse.isSelected() && (Boolean) value;
        }
        return true;
    }

    public static boolean accept(Class<?> clazz) {
        return clazz == Boolean.class;
    }

    @Override
    public boolean hasFiltersApplied() {
        return chkActivate.isSelected();
    }

}
