/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StringFilter.java
 *
 * Created on 12.10.2010, 09:56:58
 */
package edacc.filter;

/**
 *
 * @author simon
 */
public class StringFilter extends javax.swing.JPanel implements FilterInterface {

    /** Creates new form StringFilter */
    public StringFilter(String name) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkActivate = new javax.swing.JCheckBox();
        lblContains = new javax.swing.JLabel();
        txtString = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edacc.EDACCApp.class).getContext().getResourceMap(StringFilter.class);
        chkActivate.setText(resourceMap.getString("chkActivate.text")); // NOI18N
        chkActivate.setName("chkActivate"); // NOI18N

        lblContains.setText(resourceMap.getString("lblContains.text")); // NOI18N
        lblContains.setName("lblContains"); // NOI18N

        txtString.setText(resourceMap.getString("txtString.text")); // NOI18N
        txtString.setName("txtString"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblContains)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtString, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkActivate))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chkActivate)
                .addComponent(lblContains)
                .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean include(Object value) {
        if (!chkActivate.isSelected()) {
            return true;
        }
        if (value instanceof String) {
            String val = (String) value;
            return val.contains(txtString.getText());
        }
        return true;
    }

    public static boolean accept(Class<?> clazz) {
        return clazz == String.class;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkActivate;
    private javax.swing.JLabel lblContains;
    private javax.swing.JTextField txtString;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean hasFiltersApplied() {
        return chkActivate.isSelected();
    }
}
